#!/bin/bash

echo "Starting gamma=2.0 processing"

for snap in {0..400}
do
        python3 profile_fit.py '2.0' '0.20' $snap --dim 3
done

echo "SFE 0.20 done"

for snap in {0..400}
do
        python3 profile_fit.py '2.0' '0.10' $snap --dim 3
done

echo "SFE 0.10 done"

for snap in {0..400}
do
        python3 profile_fit.py '2.0' '0.05' $snap --dim 3
done

echo "SFE 0.05 done"

