#!/bin/bash

echo "Starting processing"

for snap in {3..997}
do
        python3 profile_fit.py '' '0.15' $snap --dim 3 --dir '/golowood-homes/Dehnen-mkhalo/Plummer/'
done

echo "SFE 0.15 done"

for snap in {3..997}
do
        python3 profile_fit.py '' '0.20' $snap --dim 3 --dir '/golowood-homes/Dehnen-mkhalo/Plummer/'
done

echo "SFE 0.20 done"

for snap in {3..997}
do
        python3 profile_fit.py '' '0.25' $snap --dim 3 --dir '/golowood-homes/Dehnen-mkhalo/Plummer/'
done

echo "SFE 0.25 done"

